### ISSUE TITLE
Installed, but nothing was added

### ISSUE THREAD

**Issue by VampInc-OG** [TehMuffinMoo/PlexLibraries#4]
Hello,

Forgive me, I have tried looking for a guide / wiki / readme which included how to set up this plugin. I even checked the Organizr reddit page and cannot find any post referencing this plugin. Could someone provide some instructions on how to set this up after installing please?

**Comment by TehMuffinMoo** [comment]
Hey, Sure.

The only requirements for it to work is that you've configured Plex as an authentication backend within Organizr and you've tested the connection from within the Plugin settings. You also want to make sure the Plex Admin username is set (to make sure the admin sees all user shares) and select which libraries you want to give users access to toggle.

If this is working, an option should become available in the drop down menu at the top right where your username is.

This will only work if you/your users are signed into Organizr using their Plex account.

Lemmy know how you get on

**Comment by VampInc-OG** [comment]
Thank you for the reply TehMuffinMoo, I am afraid though I do not fully understand your comment. If by "configure Plex as an authentication backend within Organizr" you mean that I have Organizr settings / Authentication set to use Plex then I have that setup and it has been working. In the same application settings page I have my Plex admin email set as the Plex Admin username. So I believe I have everything setup like you have stated, but I do not see any drop down for this plugin. *Note I sign into Organizr using Plex like you stated.

Version: 2.1.730
Branch: v2-master
Server OS: win
PHP: 7.3.9
Install Type: Native
Auth Type: both
Auth Backend: plex
Installed Plugins: Nginx Configurator:1.0.1|Plex Libraries:1.0.0
Installed Themes: 
Theme: Organizr
Local: false
oAuth: true
Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

**Comment by TehMuffinMoo** [comment]
Hey, thanks.

Should be easy enough to figure out.

Are you on discord?

**Comment by VampInc-OG** [comment]
Yes I am

**Comment by TehMuffinMoo** [comment]
This was due to the changes in Dev for removing the additional [] brackets, but the updated plugin was available in master.
- Required changes for plugin now available in Organizr master branch
