### ISSUE TITLE
Plugin unable to update

### ISSUE THREAD

**Issue by VampInc-OG** [TehMuffinMoo/PlexLibraries#6]
Hello Sir,

I am unable to install the update you have pushed, it is giving me the following error message:
Install Failed
Minimum Organizr version needed: 2.1.1030

This is what I am currently running.
Organizr Version 2.1.1030
Organizr Branch v2-master

**Comment by TehMuffinMoo** [comment]
Hey @VampInc-OG 

See this issue [#1739](https://github.com/causefx/Organizr/issues/1739)

It was related to an issue in the marketplace code which has been fixed in the dev branch. You can either pull the latest version of dev or wait for the changes to be pushed to the master branch. 😄

**Comment by VampInc-OG** [comment]
Perfect, thank you sir! I just wanted to make sure you were aware of it :) I hope you have a good day!

**Comment by TehMuffinMoo** [comment]
Resolved now in Organizr master
